refactor: use two-space indents (#54)

diff --git a/flash_your_device b/flash_your_device
--- a/flash_your_device
+++ b/flash_your_device
@@ -32,91 +32,91 @@ echo "------------------------------------------------------------"
 echo
 
 if [ "$(whoami)" = "root" ]; then
-    echo -e "ALERT: You're running the script as root/superuser.\nYou may notice PIP 'sudo -H' warnings.\n"
+  echo -e "ALERT: You're running the script as root/superuser.\nYou may notice PIP 'sudo -H' warnings.\n"
 fi
 
 case "$(uname -s)" in
-    Linux*)
-        machine="Linux"
-        echo "Detected ${machine}."
-        echo -n "Checking for dependencies... "
-        if ! command -v cmake &>/dev/null; then
-            echo -e "\n\nERROR:\ncmake was not found on your system.\nPlease install cmake by running:\n\nsudo apt update && sudo apt install -y cmake\n"
-            exit 1
-        elif ! command -v git &>/dev/null; then
-            echo -e "\n\nERROR:\ngit was not found on your system.\nPlease install git by running:\n\nsudo apt update && sudo apt install -y git\n"
-            exit 1
-        elif ! command -v pip &>/dev/null; then
-            echo -e "\n\nERROR:\npip was not found on your system.\nPlease install pip by running:\n\nsudo apt update && sudo apt install -y python3-pip\n"
-            exit 1
-        elif ! command -v virtualenv &>/dev/null; then
-            echo -e "\n\nERROR:\nvirtualenv was not found on your system.\nPlease install virtualenv by running:\n\nsudo apt update && sudo apt install -y python3-virtualenv\n"
-            exit 1
+  Linux*)
+    machine="Linux"
+    echo "Detected ${machine}."
+    echo -n "Checking for dependencies... "
+    if ! command -v cmake &>/dev/null; then
+      echo -e "\n\nERROR:\ncmake was not found on your system.\nPlease install cmake by running:\n\nsudo apt update && sudo apt install -y cmake\n"
+      exit 1
+    elif ! command -v git &>/dev/null; then
+      echo -e "\n\nERROR:\ngit was not found on your system.\nPlease install git by running:\n\nsudo apt update && sudo apt install -y git\n"
+      exit 1
+    elif ! command -v pip &>/dev/null; then
+      echo -e "\n\nERROR:\npip was not found on your system.\nPlease install pip by running:\n\nsudo apt update && sudo apt install -y python3-pip\n"
+      exit 1
+    elif ! command -v virtualenv &>/dev/null; then
+      echo -e "\n\nERROR:\nvirtualenv was not found on your system.\nPlease install virtualenv by running:\n\nsudo apt update && sudo apt install -y python3-virtualenv\n"
+      exit 1
+    fi
+    echo "ok."
+    ;;
+  Darwin*)
+    machine="macOS"
+    echo "Detected ${machine}."
+    echo -n "Checking for cmake... "
+    if ! command -v cmake &>/dev/null; then
+      if [ ! -d /Applications/CMake.app ]; then
+        #read -srk "?  CMake is not found in your Applications directory.\n  PRESS ANY KEY to download CMake... " && echo
+        #cmake_macos_url="https://github.com/Kitware/CMake/releases/download/v3.26.4/cmake-3.26.4-macos-universal.tar.gz"
+        #cmake_macos_tarball="${HOME}"/$(basename "${cmake_macos_url}")
+        #cmake_macos_extract_dir="${HOME}/$(basename "${cmake_macos_url}" .tar.gz)"
+        #wget -P "${HOME}" "${cmake_macos_url}"
+        #tar -xf "${cmake_macos_tarball}" -C "${HOME}/"
+        #cp -r "${cmake_macos_extract_dir}"/CMake.app/ /Applications/CMake.app/
+        cmake_macos_url="https://github.com/Kitware/CMake/releases/download/v3.26.4/cmake-3.26.4-macos-universal.dmg"
+        cmake_macos_dmg="$(basename ${cmake_macos_url})"
+        #cmake_macos_volume="/Volumes/$(basename ${cmake_macos_url} .dmg)"
+        
+        if [ ! -f "${HOME}"/Downloads/"${cmake_macos_dmg}" ]
+        then
+          echo -ne "\n  Downloading CMake... "
+          #wget --quiet -P "${HOME}" "${cmake_macos_url}"
+          #wget --quiet -P "${HOME}/Downloads" "${cmake_macos_url}"
+          curl -sL "${cmake_macos_url}" --output "${HOME}"/Downloads/"${cmake_macos_dmg}"
+          echo "ok."
         fi
-        echo "ok."
-        ;;
-    Darwin*)
-        machine="macOS"
-        echo "Detected ${machine}."
-        echo -n "Checking for cmake... "
-        if ! command -v cmake &>/dev/null; then
-            if [ ! -d /Applications/CMake.app ]; then
-                #read -srk "?  CMake is not found in your Applications directory.\n  PRESS ANY KEY to download CMake... " && echo
-                #cmake_macos_url="https://github.com/Kitware/CMake/releases/download/v3.26.4/cmake-3.26.4-macos-universal.tar.gz"
-                #cmake_macos_tarball="${HOME}"/$(basename "${cmake_macos_url}")
-                #cmake_macos_extract_dir="${HOME}/$(basename "${cmake_macos_url}" .tar.gz)"
-                #wget -P "${HOME}" "${cmake_macos_url}"
-                #tar -xf "${cmake_macos_tarball}" -C "${HOME}/"
-                #cp -r "${cmake_macos_extract_dir}"/CMake.app/ /Applications/CMake.app/
-                cmake_macos_url="https://github.com/Kitware/CMake/releases/download/v3.26.4/cmake-3.26.4-macos-universal.dmg"
-                cmake_macos_dmg="$(basename ${cmake_macos_url})"
-                #cmake_macos_volume="/Volumes/$(basename ${cmake_macos_url} .dmg)"
-                
-                if [ ! -f "${HOME}"/Downloads/"${cmake_macos_dmg}" ]
-                then
-                    echo -ne "\n  Downloading CMake... "
-                    #wget --quiet -P "${HOME}" "${cmake_macos_url}"
-                    #wget --quiet -P "${HOME}/Downloads" "${cmake_macos_url}"
-                    curl -sL "${cmake_macos_url}" --output "${HOME}"/Downloads/"${cmake_macos_dmg}"
-                    echo "ok."
-                fi
 
-                echo -e "\n************************************************************"
-                echo "ERROR: Automatic installation of CMake is not supported yet."
-                echo "Please manually install ${cmake_macos_dmg}."
-                echo "Please open the file from your Downloads folder."
-                echo -e "************************************************************\n"
-                exit 1
-                
-                #echo -n "  Installing cmake..."
-                #hdiutil attach -quiet -nobrowse "${HOME}"/"${cmake_macos_dmg}"
-                #cp -r ${cmake_macos_volume}/CMake.app/ /Applications/CMake.app/
-                #hdiutil detach -quiet ${cmake_macos_volume}
-                #rm "${HOME}"/"${cmake_macos_dmg}"
-                #echo "ok."
-            fi
-            PATH="/Applications/CMake.app/Contents/bin${PATH:+:${PATH}}"
-        fi
-        echo "ok."
-        ;;
-    MINGW*)
-        echo "Windows is not supported. Please run in WSL (Windows Subsystem for Linux)." && exit 0;;
-    *) echo "Unsupported OS: $(uname -s)" && exit 0
+        echo -e "\n************************************************************"
+        echo "ERROR: Automatic installation of CMake is not supported yet."
+        echo "Please manually install ${cmake_macos_dmg}."
+        echo "Please open the file from your Downloads folder."
+        echo -e "************************************************************\n"
+        exit 1
+        
+        #echo -n "  Installing cmake..."
+        #hdiutil attach -quiet -nobrowse "${HOME}"/"${cmake_macos_dmg}"
+        #cp -r ${cmake_macos_volume}/CMake.app/ /Applications/CMake.app/
+        #hdiutil detach -quiet ${cmake_macos_volume}
+        #rm "${HOME}"/"${cmake_macos_dmg}"
+        #echo "ok."
+      fi
+      PATH="/Applications/CMake.app/Contents/bin${PATH:+:${PATH}}"
+    fi
+    echo "ok."
+    ;;
+  MINGW*)
+    echo "Windows is not supported. Please run in WSL (Windows Subsystem for Linux)." && exit 0;;
+  *) echo "Unsupported OS: $(uname -s)" && exit 0
 esac
 
 echo -n "Checking for the Espressif IoT Development Framework... "
 if [ ! -f "${esp_idf_save_directory}"/export.sh ]; then
-    echo -ne "\n  Downloading the framework... "
-    git -c advice.detachedHead=false clone --branch "${esp_idf_git_tag}" --single-branch --depth 1 --quiet "${esp_idf_repo_url}" "${esp_idf_temp_directory}"
-    cd "${esp_idf_temp_directory}"/
-    git submodule update --depth 1 --init --recursive --quiet &> /dev/null
-    ./install.sh esp32 &>/dev/null
-    # shellcheck source=/dev/null
-    source ./export.sh 1>/dev/null
-    mv "${esp_idf_temp_directory}" "${esp_idf_save_directory}"
-    echo "ok."
+  echo -ne "\n  Downloading the framework... "
+  git -c advice.detachedHead=false clone --branch "${esp_idf_git_tag}" --single-branch --depth 1 --quiet "${esp_idf_repo_url}" "${esp_idf_temp_directory}"
+  cd "${esp_idf_temp_directory}"/
+  git submodule update --depth 1 --init --recursive --quiet &> /dev/null
+  ./install.sh esp32 &>/dev/null
+  # shellcheck source=/dev/null
+  source ./export.sh 1>/dev/null
+  mv "${esp_idf_temp_directory}" "${esp_idf_save_directory}"
+  echo "ok."
 else
-    echo
+  echo
 fi
 cd "${esp_idf_save_directory}"
 echo -ne "  Installing the framework... "
@@ -128,10 +128,10 @@ echo "ok."
 
 echo -n "Checking for the Blockstream Jade repository... "
 if [ ! -d "${jade_save_directory}" ]; then
-    echo -ne "\n  Downloading Jade... "
-    git -c advice.detachedHead=false clone --branch "${jade_git_tag}" --single-branch --depth 1 --quiet "${jade_repo_url}" "${jade_save_directory}"
-    cd "${jade_save_directory}"
-    git submodule update --depth 1 --init --recursive --quiet &> /dev/null
+  echo -ne "\n  Downloading Jade... "
+  git -c advice.detachedHead=false clone --branch "${jade_git_tag}" --single-branch --depth 1 --quiet "${jade_repo_url}" "${jade_save_directory}"
+  cd "${jade_save_directory}"
+  git submodule update --depth 1 --init --recursive --quiet &> /dev/null
 fi
 cd "${jade_save_directory}"
 jade_version="$(git describe --tags)"
@@ -142,37 +142,37 @@ PS3='Please enter the number for your device or QUIT: '
 options=("${device1}" "${device2}" "${device3}" "${device4}" "QUIT")
 select choice in "${options[@]}"
 do
-    case "${choice}" in
-        "${device1}")
-            tty_device="/dev/ttyACM0"
-            flash_command="idf.py flash"
-            cp configs/sdkconfig_display_ttgo_tdisplay.defaults sdkconfig.defaults
-            break
-            ;;
-        "${device2}")
-            tty_device="/dev/ttyUSB0"
-            flash_command="idf.py -b 115200 flash"
-            cp configs/sdkconfig_display_m5stickcplus.defaults sdkconfig.defaults
-            break
-            ;;
-        "${device3}")
-            tty_device="/dev/ttyACM0"
-            flash_command="idf.py flash"
-            cp configs/sdkconfig_display_m5blackgray.defaults sdkconfig.defaults
-            break
-            ;;
-        "${device4}")
-            tty_device="/dev/ttyACM0"
-            flash_command="idf.py flash"
-            cp configs/sdkconfig_display_m5fire.defaults sdkconfig.defaults
-            break
-            ;;
-        "QUIT")
-            echo "You chose to quit."
-            exit 0
-            ;;
-        *) echo "You entered ${REPLY}, which is invalid."
-    esac
+  case "${choice}" in
+    "${device1}")
+      tty_device="/dev/ttyACM0"
+      flash_command="idf.py flash"
+      cp configs/sdkconfig_display_ttgo_tdisplay.defaults sdkconfig.defaults
+      break
+      ;;
+    "${device2}")
+      tty_device="/dev/ttyUSB0"
+      flash_command="idf.py -b 115200 flash"
+      cp configs/sdkconfig_display_m5stickcplus.defaults sdkconfig.defaults
+      break
+      ;;
+    "${device3}")
+      tty_device="/dev/ttyACM0"
+      flash_command="idf.py flash"
+      cp configs/sdkconfig_display_m5blackgray.defaults sdkconfig.defaults
+      break
+      ;;
+    "${device4}")
+      tty_device="/dev/ttyACM0"
+      flash_command="idf.py flash"
+      cp configs/sdkconfig_display_m5fire.defaults sdkconfig.defaults
+      break
+      ;;
+    "QUIT")
+      echo "You chose to quit."
+      exit 0
+      ;;
+    *) echo "You entered ${REPLY}, which is invalid."
+  esac
 done
 chosen_device="${choice}"
 echo
@@ -182,32 +182,32 @@ sed -i.bak '/CONFIG_DEBUG_MODE/d' ./sdkconfig.defaults
 sed -i.bak '1s/^/CONFIG_LOG_DEFUALT_LEVEL_NONE=y\n/' sdkconfig.defaults
 
 case "${machine}" in
-    Linux*)
-        while [ ! -c "${tty_device}" ]; do
-            read -srn1 -p "Connect your ${chosen_device} and PRESS ANY KEY to continue... " && echo
-        done
-        tty_device_permissions="$(stat -c '%a' "${tty_device}")"
-        if [ "${tty_device_permissions:2}" -lt 6 ]; then
-            echo -e "ERROR:\nYou need elevated permissions to write to the device.\nPlease update your device permissoins by running:\n\nsudo chmod o+rw ${tty_device}\n"
-            exit 1
-        fi
-        ;;
-    macOS*)
-        #macos_usb_serial=$(ioreg -p IOUSB -n "USB Single Serial" | grep "USB Serial Number" | cut -c 34-43)
-        
-        #[ -z "${macos_usb_serial}" ] && echo "serial does not exist"
-        
-        #while [ -z "${macos_usb_serial}" ]
-        #do
-        #    echo -e "Connect your ${chosen_device} with a USB-C cable,\n  click \"Allow\" if you see a macOS security popup,"
-        #    sleep 5
-        #    macos_usb_serial=$(ioreg -p IOUSB -n "USB Single Serial" | grep "USB Serial Number" | cut -c 34-43)
+  Linux*)
+    while [ ! -c "${tty_device}" ]; do
+      read -srn1 -p "Connect your ${chosen_device} and PRESS ANY KEY to continue... " && echo
+    done
+    tty_device_permissions="$(stat -c '%a' "${tty_device}")"
+    if [ "${tty_device_permissions:2}" -lt 6 ]; then
+      echo -e "ERROR:\nYou need elevated permissions to write to the device.\nPlease update your device permissoins by running:\n\nsudo chmod o+rw ${tty_device}\n"
+      exit 1
+    fi
+    ;;
+  macOS*)
+    #macos_usb_serial=$(ioreg -p IOUSB -n "USB Single Serial" | grep "USB Serial Number" | cut -c 34-43)
+    
+    #[ -z "${macos_usb_serial}" ] && echo "serial does not exist"
+    
+    #while [ -z "${macos_usb_serial}" ]
+    #do
+    #    echo -e "Connect your ${chosen_device} with a USB-C cable,\n  click \"Allow\" if you see a macOS security popup,"
+    #    sleep 5
+    #    macos_usb_serial=$(ioreg -p IOUSB -n "USB Single Serial" | grep "USB Serial Number" | cut -c 34-43)
 
-        #done
-        echo -e "Connect your ${chosen_device} with a USB-C cable,\n  and click Allow if you see a security popup."
-        read -srn1 -p "  PRESS ANY KEY to continue... " && echo && echo
-        ;;
-    *) echo "Unsupported OS: $(uname -s)" && exit 0
+    #done
+    echo -e "Connect your ${chosen_device} with a USB-C cable,\n  and click Allow if you see a security popup."
+    read -srn1 -p "  PRESS ANY KEY to continue... " && echo && echo
+    ;;
+  *) echo "Unsupported OS: $(uname -s)" && exit 0
 esac
 
 echo -e "Ready to install Jade ${jade_version} on your ${chosen_device}.\n  (This process can take over 10 minutes.)"
